Feature/task 20 django app
jaagomezmu/myblog pull request #20
Opened 2023-04-24 06:31 UTC by jaagomezmu

2023-04-24 17:25 UTC, ejariza-evowill requested changes

2023-04-24 17:25 UTC, ejariza-evowill commented on myblog/blog/views.py
> +        return CommentSerializer
CommentViewSet should also implement LikesModelMixin

2023-04-25 00:17 UTC, jaagomezmu commented on myblog/blog/views.py
> +        return CommentSerializer
Got it!

2023-04-27 18:13 UTC, ejariza-evowill approved these changes

2023-04-27 18:14 UTC, merged